### ISSUE TITLE
aes-256-cbc encryption does not produce reproducible results

### ISSUE THREAD

**Issue by tuhlmann** [wheresvic/mongoose-field-encryption#24]
I updated my project to version 2.0.0 of your lib.
Now it seems every time I encrypt the same string value the created encrypted string is different. Looking into the code the reason seems the iv value that is recreated every time.

Having a different salt each time provides for stronger encryption , but on the other hand the value can't be searched for.

I'd suggest passing the salt value the same way secret is passed. It me also be of value to provide a callback function that produces the salt instead of passing the same string for the whole collection. In another project we're using the company _id as salt value.

**Comment by wheresvic** [comment]
Hi @tuhlmann 

Yes, this is why this was a major change, see https://github.com/wheresvic/mongoose-field-encryption#200. In order to maintain previous behaviour you can set the `useAes256Ctr` flag to true and it will fallback to using the previous algorithm without the salt.

We can also look into adding the salt generation as a parameter or function - I'll take it up for the next release!

**Comment by Ionut-Milas** [comment]
any update on this ?

**Comment by wheresvic** [comment]
@Ionut-Milas Sorry for the delay in getting back to you - it is on my radar and I will try to get this done this week :)

**Comment by wheresvic** [comment]
@tuhlmann @Ionut-Milas this is now resolved via #28. Please have a look at v2.3.0 and feel free to reach out in case there are more issues, cheers!
