### ISSUE TITLE
Bad decrypt when retrieving multiple docs from DB

### ISSUE THREAD

**Issue by Glacian22** [wheresvic/mongoose-field-encryption#54]
I'm currently running v3.0.4, and everything works great when finding a single doc. 

ex: `db.User.findById('someid)` will find that user and decrypt the encrypted fields (name and email). But trying to find multiple docs, like `db.User.find()` which should retrieve all users, I get a bad decrypt error. 

Currently I'm using a workaround where I only ask mongoose for the fields I want, minus the __enc flag fields, `db.User.find({}, 'name email')`, and then loop through, add in the __enc flags, and run decryptFieldsSync(). But obviously that's kind of an ugly hack.

Am I doing something wrong here, or does the package not support bulk decryption?

**Comment by wheresvic** [comment]
Hi @Glacian22 

Yes unfortunately this is a limitation of mongoose itself: https://mongoosejs.com/docs/middleware.html#notes

This problem is that `find` is a generic query on all documents and Mongoose does not have a reference to the document object when it is doing such a find, hence it cannot execute the plugin. So what you are doing is ugly yes, but it is actually the correct approach!

Cheers,

**Comment by Glacian22** [comment]
Thanks for the clarification, much appreciated!
