### ISSUE TITLE
Searching RegEx / Case Insensitive Encrypted Fields

### ISSUE THREAD

**Issue by sators** [wheresvic/mongoose-field-encryption#76]
Is it possible to use a RegEx value to search case insensitive through encrypted fields?

**Comment by wheresvic** [comment]
@sators Yes, as long as you use a _fixed salt generator_, you can search over encrypted values: https://github.com/wheresvic/mongoose-field-encryption#search-over-encrypted-fields

Fun fact: this project was actually started out because I needed the ability to search over encrypted values. However do note that this is approach *not recommended due to insufficient security requirements*.

You could consider building some sort of a trie/index data structure that indexes interesting keywords and links them to documents (sort of like google search). Anyways depending upon your threat model and use case, you have options.

**Comment by sators** [comment]
Thanks for the tip!
