### ISSUE TITLE
#minor: Use in memory mongo for tests

### ISSUE THREAD

**Issue by adidaslevy** [wheresvic/mongoose-field-encryption#95]
Currently, you have to have a running instance of mongoDB for running tests. 
In memory DB will spare that requirement.

**Comment by wheresvic** [comment]
@adidaslevy the idea behind running integration tests is that we actually test against a production-like setup with a real db. Given that docker makes it really cheap to get a db up and running, I quite prefer the current setup. 

You can look into scripting it so that the test starts the db on its own and stops it when it is finished. Generally, when I'm working on the plugin I have a hook that keeps running the tests so having the docker container running is more efficient.

**Comment by adidaslevy** [comment]
Sorry, I was sick for some days... just got back. 
Ok, so the preference is to have a real mongo.
Cool, NP.
